title:            echo "new stuff" >> hanmoi.choi
description:      A jekyll theme. Because I scribble.
url:              hanmoi-choi.github.io
signoff:          Hanmoi Choi
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://hanmoi-choi.github.io
    external:     true
  - name:         Email
    url:          mailto:forhim185@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/hanmoi-choi
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
